import {Inter} from 'next/font/google'
import './globals.css'
import localFont from "next/font/local";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
const rem = localFont({
    src: [
        {
            path: '../../public/assets/fonts/rem/REM-Bold.ttf',
            weight: '600',
            style: 'normal',
        }
    ],
})
export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={rem.className}>{children}</body>
        </html>
    )
}
